language: python
python:
  - '3.6'

notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64
           PLAT=manylinux2010_x86_64

env:
  global:
    - TWINE_USERNAME=pgdr
    # Note: TWINE_PASSWORD is set in Travis settings

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
  - ls wheelhouse/
  - python3 -m pip install --upgrade pip twine
  - python3 -m twine upload wheelhouse/*.whl
  - python3 -m pip install --upgrade minisat
  - python3 -c "import minisat"
